FROM ubuntu:16.04
MAINTAINER d.ermizin <kernel218@gmail.com>
USER root
RUN apt-get update -q && apt-get install -yq git \
    docker.io \
    && rm -rf /var/cache/apk/*
CMD /etc/init.d/docker start && /bin/bash
#CMD ["/etc/init.d/docker" 'start'